-- Conecta no schema do usuário
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = intersolid;

-- Tabela CBS/IBS
CREATE TABLE MXF_TMP_CBS_IBS (
  codigo_produto   VARCHAR2(60),
  ean              NUMBER(14),
  cclasstrib       VARCHAR2(6),
  cst_cbs_ibs      VARCHAR2(3),
  alq_cbs          NUMBER(7,3),
  rbc_cbs          NUMBER(7,3),
  alq_ibs          NUMBER(7,3),
  alq_ibs_mun      NUMBER(7,3),
  rbc_ibs          NUMBER(7,3),
  rbc_ibs_mun      NUMBER(7,3),
  alq_is           NUMBER(7,3),
  alq_is_espec     NUMBER(7,3),
  cst_is           VARCHAR2(3),
  cclasstrib_is    VARCHAR2(6),
  fundamento_legal VARCHAR2(500),
  dta_alteracao    DATE DEFAULT SYSDATE NOT NULL,
  dta_cadastro     DATE DEFAULT SYSDATE NOT NULL,
  des_sigla        VARCHAR2(2),
  tipo_regime      NUMBER(5) DEFAULT 0 NOT NULL
);

-- Tabela ICMS Entrada
CREATE TABLE MXF_TMP_ICMS_ENTRADA (
  codigo_produto    VARCHAR2(60),
  ean               NUMBER(14),
  tipo_mva          VARCHAR2(2),
  mva               NUMBER(7,3),
  mva_data_ini      DATE,
  mva_data_fim      DATE,
  credito_outorgado NUMBER(10),
  gera_debito       NUMBER(10),
  sub_rbc_alq       NUMBER(10),
  ei_cst            VARCHAR2(3),
  ei_alq            NUMBER(7,3),
  ei_alqst          NUMBER(7,3),
  ei_rbc            NUMBER(7,3),
  ei_rbcst          NUMBER(7,3),
  ed_cst            VARCHAR2(3),
  ed_alq            NUMBER(7,3),
  ed_alqst          NUMBER(7,3),
  ed_rbc            NUMBER(7,3),
  ed_rbcst          NUMBER(7,3),
  es_cst            VARCHAR2(3),
  es_alq            NUMBER(7,3),
  es_alqst          NUMBER(7,3),
  es_rbc            NUMBER(7,3),
  es_rbcst          NUMBER(7,3),
  nfi_cst           VARCHAR2(3),
  nfd_cst           VARCHAR2(3),
  nfs_csosn         VARCHAR2(4),
  nf_alq            NUMBER(7,3),
  fundamento_legal  VARCHAR2(500),
  ncm               VARCHAR2(10),
  dta_alteracao     DATE DEFAULT SYSDATE NOT NULL,
  dta_cadastro      DATE DEFAULT SYSDATE NOT NULL,
  des_sigla         CHAR(2),
  tipo_regime       NUMBER(5) DEFAULT 0 NOT NULL
);

-- Tabela ICMS Saída
CREATE TABLE MXF_TMP_ICMS_SAIDA (
  codigo_produto   VARCHAR2(60),
  ean              NUMBER(14),
  sac_cst          VARCHAR2(3),
  sac_alq          NUMBER(7,3),
  sac_alqst        NUMBER(7,3),
  sac_rbc          NUMBER(7,3),
  sac_rbcst        NUMBER(7,3),
  sas_cst          VARCHAR2(3),
  sas_alq          NUMBER(7,3),
  sas_alqst        NUMBER(7,3),
  sas_rbc          NUMBER(7,3),
  sas_rbcst        NUMBER(7,3),
  svc_cst          VARCHAR2(3),
  svc_alq          NUMBER(7,3),
  svc_alqst        NUMBER(7,3),
  svc_rbc          NUMBER(7,3),
  svc_rbcst        NUMBER(7,3),
  snc_cst          VARCHAR2(3),
  snc_alq          NUMBER(7,3),
  snc_alqst        NUMBER(7,3),
  snc_rbc          NUMBER(7,3),
  snc_rbcst        NUMBER(7,3),
  fundamento_legal VARCHAR2(500),
  ncm              VARCHAR2(10),
  cest             VARCHAR2(10),
  fecp             NUMBER(7,3),
  snc_cbenef       VARCHAR2(10),
  snc_alq_benef    NUMBER(7,3),
  sac_cbenef       VARCHAR2(10),
  sac_alq_benef    NUMBER(7,3),
  sss_csosn        VARCHAR2(4),
  dta_alteracao    DATE DEFAULT SYSDATE NOT NULL,
  dta_cadastro     DATE DEFAULT SYSDATE NOT NULL,
  des_sigla        CHAR(2),
  tipo_regime      NUMBER(5) DEFAULT 0 NOT NULL
);

-- Tabela Produtos
CREATE TABLE MXF_TMP_PRODUTOS (
  codigo_produto   VARCHAR2(60),
  ean              NUMBER(14),
  ncm              VARCHAR2(10),
  icms_cst_e       VARCHAR2(3),
  icms_cst_s       VARCHAR2(3),
  icms_alqt_e      NUMBER(7,3),
  icms_alqt_s      NUMBER(7,3),
  icms_rbc_e       NUMBER(7,3),
  icms_rbc_s       NUMBER(7,3),
  tipo_iva         VARCHAR2(7),
  iva              NUMBER(7,3),
  pis_e            VARCHAR2(3),
  pis_s            VARCHAR2(3),
  pis_alqt_e       NUMBER(7,3),
  pis_alqt_s       NUMBER(7,3),
  pis_cst_e        VARCHAR2(3),
  pis_cst_s        VARCHAR2(3),
  cofins_e         VARCHAR2(3),
  cofins_s         VARCHAR2(3),
  cofins_alqt_e    NUMBER(7,3),
  cofins_alqt_s    NUMBER(7,3),
  cofins_cst_e     VARCHAR2(3),
  cofins_cst_s     VARCHAR2(3),
  fundamento_legal VARCHAR2(500),
  id_ncm           NUMBER(10),
  des_sigla        CHAR(2),
  tipo_regime      NUMBER(5) DEFAULT 0 NOT NULL
);

SELECT 'Tabelas criadas com sucesso!' FROM DUAL;